"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import pydantic
from pydantic import model_serializer
from tofupilot.v2.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from tofupilot.v2.utils import FieldMetadata, PathParamMetadata, RequestMetadata
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class ProcedureUpdateRequestBodyTypedDict(TypedDict):
    name: NotRequired[str]
    r"""New name for the procedure."""
    auto_deploy_branch: NotRequired[Nullable[str]]
    r"""Branch name that triggers auto-deploy to all linked stations. Set to null to disable."""


class ProcedureUpdateRequestBody(BaseModel):
    name: Optional[str] = None
    r"""New name for the procedure."""

    auto_deploy_branch: Annotated[
        OptionalNullable[str], pydantic.Field(alias="autoDeployBranch")
    ] = UNSET
    r"""Branch name that triggers auto-deploy to all linked stations. Set to null to disable."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = ["name", "autoDeployBranch"]
        nullable_fields = ["autoDeployBranch"]
        null_default_fields = []

        serialized = handler(self)

        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            serialized.pop(k, None)

            optional_nullable = k in optional_fields and k in nullable_fields
            is_set = (
                self.__pydantic_fields_set__.intersection({n})
                or k in null_default_fields
            )  # pylint: disable=no-member

            if val is not None and val != UNSET_SENTINEL:
                m[k] = val
            elif val != UNSET_SENTINEL and (
                not k in optional_fields or (optional_nullable and is_set)
            ):
                m[k] = val

        return m


class ProcedureUpdateRequestTypedDict(TypedDict):
    id: str
    r"""Unique identifier of the procedure to update."""
    request_body: ProcedureUpdateRequestBodyTypedDict


class ProcedureUpdateRequest(BaseModel):
    id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""Unique identifier of the procedure to update."""

    request_body: Annotated[
        ProcedureUpdateRequestBody,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]


class ProcedureUpdateResponseTypedDict(TypedDict):
    r"""Procedure updated successfully"""

    id: str
    r"""Unique identifier of the updated procedure."""


class ProcedureUpdateResponse(BaseModel):
    r"""Procedure updated successfully"""

    id: str
    r"""Unique identifier of the updated procedure."""
